<?php

namespace Album\Model;

use \Doctrine\ORM\EntityRepository;
/**
 * AlbumDao
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumDao extends EntityRepository
{
    
}
