<?php

namespace Album\Model;

/**
 * AlbumDao
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumDao extends \Doctrine\ORM\EntityRepository
{
}
