<h1> Edit</h1>
<?php
/**
 * @var $form \Zend\Form\Form
 */
$this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-error"><button type"button" class="close" data-dismiss="alert">x</button>')
    ->setMessageCloseString('</div>')
    ->render($form);
$form->setAttribute('action', $this->url('album', ['controller' => 'album','action' => 'edit', 'id' => $id]));
$form->prepare();
echo $this->form()->openTag($form);

echo $this->formCollection($form);

echo $this->form()->closeTag($form);
?>